### PR TITLE
add support for one part of App Annie's intelligence api

### PR DESCRIPTION
**Pull request by dylanjha**
- AppAnnie::Intelligence.top_app_charts
- specify rspec version in gemspec (this was leading to a travis bug)
- AppAnnie::ErrorResponse.raise_for(response)- remove some code-duplication that was handling errors

### CODE REVIEW

**Comment by dylanjha** [comment]
@modeset, do you have any interest in enhancing this library to include App Annie's Intelligence API?

**Comment by jayzes** [comment]
Yes, for sure. Can you check into the failing Travis build though?

**Comment by dylanjha** [comment]
the build failure is really strange.  Error in the rspec dsl, almost like rspec didn't load or something, can't replicate locally, even with the exact same ruby version `1.9.3-p545`  Then same thing happened with travis on an upgraded ruby... any ideas?:

```
/home/travis/build/modeset/app_annie/spec/account_spec.rb:17
undefined method `its' for RSpec::ExampleGroups::AppAnnieAccount::BuildingAnAccountFromAHash:Class (NoMethodError)
```

**Comment by dylanjha** [comment]
o, I see... travis is using rspec-core-3 even though Gemfile.lock specifies rspec-core-2.14.7.  Shouldn't the `bundle exec` be not allowing this?
travis_ci_-_free_hosted_continuous_integration_platform_for_the_open_source_community

**Comment by dylanjha** [comment]
Am I expected to fix all the houndci notes? Many are contradictory to examples I already see in the app.

**Comment by jayzes** [comment]
No worries on the Hound notes. I need to set up a Hound config for the project to ignore the ones I don't like, haha.

**Comment by jayzes** [comment]
On the rspec issue - we should tighten down the required rspec version in the gemspec rather than checking in a Gemfile.lock

**Comment by dylanjha** [comment]
o ya, you're right, just read this: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ 

.. thx, will fix, rebase these commits so they look nice.

**Comment by dylanjha** [comment]
ready for you to have a look @jayzes , @modeset I added a few more things

**Comment by jayzes** [comment]
:thumbsup: 

I like the condensed error response handling, nice!

**Pull request merged**
